apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-api-role
  namespace: api
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["list", "get", "describe", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: write-api-role
  namespace: api
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-write-bind
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: write-api-role
subjects:
- kind: Group
  namespace: api
  name: "3cbd226d-08b2-40c8-be76-f84217af2341"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-read-bind
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-api-role
subjects:
- kind: Group
  namespace: api
  name: "646ab333-0ac4-41be-8a3c-1c0f291be18b"