apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-web-role
  namespace: web
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["list", "get", "describe", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: write-web-role
  namespace: web
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-write-bind
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: write-web-role
subjects:
- kind: Group
  namespace: web
  name: "646ab333-0ac4-41be-8a3c-1c0f291be18b"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-read-bind
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-web-role
subjects:
- kind: Group
  namespace: web
  name: "3cbd226d-08b2-40c8-be76-f84217af2341"