apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akvname-api-csi
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "openhack4KeyVault"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "910b2490-e0e2-48ed-af9d-4a8a28f7a49e"
    cloudName: ""
    tenantId: "74c5e94a-6c75-4c45-b7fe-0a020e668cbe"
    objects: |
      array:
        - |
          objectName: "sql-user"
          objectType: secret
        - |
          objectName: "sql-password"
          objectType: secret
        - |
          objectName: "sql-server"
          objectType: secret
        - |
          objectName: "sql-dbname"
          objectType: secret
  secretObjects:
    - secretName: "openhacksecret"
      data:
      - key: sql_user
        objectName: "sql-user"
      - key: sql_password
        objectName: "sql-password"
      - key: sql_server
        objectName: "sql-server"
      - key: sql_dbname
        objectName: "sql-dbname"
      type: Opaque
