apiVersion: apps/v1
kind: Deployment
metadata:
  name: oh-poi
  namespace: api
spec:
  selector:
    matchLabels:
      app: oh-poi
  template:
    metadata:
      labels:
        app: oh-poi
    spec:
      containers:
      - name: poi
        image: registryznq7406.azurecr.io/openhack/poi:latest
        volumeMounts:
          - mountPath: "/mnt/secrets-store"
            name: secrets-store
            readOnly: true
        env:
        - name: "SQL_USER"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_user
        - name: "SQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_password
        - name: "SQL_SERVER"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_server
        - name: "SQL_DBNAME"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_dbname
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Local"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: akvname-api-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oh-trips
  namespace: api
spec:
  selector:
    matchLabels:
      app: oh-trips
  template:
    metadata:
      labels:
        app: oh-trips
    spec:
      containers:
      - name: trips
        image: registryznq7406.azurecr.io/openhack/trips:latest
        volumeMounts:
          - mountPath: "/mnt/secrets-store"
            name: secrets-store
            readOnly: true
        env:
        - name: "SQL_USER"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_user
        - name: "SQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_password
        - name: "SQL_SERVER"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_server
        - name: "SQL_DBNAME"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_dbname
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: akvname-api-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oh-user-java
  namespace: api
spec:
  selector:
    matchLabels:
      app: oh-user-java
  template:
    metadata:
      labels:
        app: oh-user-java
    spec:
      containers:
      - name: user-java
        image: registryznq7406.azurecr.io/openhack/user-java:latest
        volumeMounts:
          - mountPath: "/mnt/secrets-store"
            name: secrets-store
            readOnly: true
        env:
        - name: "SQL_USER"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_user
        - name: "SQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_password
        - name: "SQL_SERVER"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_server
        - name: "SQL_DBNAME"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_dbname
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
        ports:
        - containerPort: 80
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: akvname-api-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oh-userprofile
  namespace: api
spec:
  selector:
    matchLabels:
      app: oh-userprofile
  template:
    metadata:
      labels:
        app: oh-userprofile
    spec:
      containers:
      - name: userprofile
        image: registryznq7406.azurecr.io/openhack/userprofile:latest
        volumeMounts:
          - mountPath: "/mnt/secrets-store"
            name: secrets-store
            readOnly: true
        env:
        - name: "SQL_USER"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_user
        - name: "SQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_password
        - name: "SQL_SERVER"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_server
        - name: "SQL_DBNAME"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_dbname
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: akvname-api-csi