apiVersion: apps/v1
kind: Deployment
metadata:
  name: oh-trips
  namespace: oh-backend
spec:
  selector:
    matchLabels:
      app: oh-trips
  template:
    metadata:
      labels:
        app: oh-trips
    spec:
      containers:
      - name: trips
        image: registryznq7406.azurecr.io/openhack/trips:latest
        env:
        - name: "SQL_USER"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_user
        - name: "SQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_password
        - name: "SQL_SERVER"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_server
        - name: "SQL_DBNAME"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_dbname
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80