apiVersion: apps/v1
kind: Deployment
metadata:
  name: oh-user-java
  namespace: oh-backend
spec:
  selector:
    matchLabels:
      app: oh-user-java
  template:
    metadata:
      labels:
        app: oh-user-java
    spec:
      containers:
      - name: user-java
        image: registryznq7406.azurecr.io/openhack/user-java:latest
        env:
        - name: "SQL_USER"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_user
        - name: "SQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_password
        - name: "SQL_SERVER"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_server
        - name: "SQL_DBNAME"
          valueFrom:
            secretKeyRef:
              name: "openhacksecret"
              key: sql_dbname
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80