apiVersion: apps/v1
kind: Deployment
metadata:
  name: oh-tripviewer-rbac
  namespace: web
spec:
  selector:
    matchLabels:
      app: oh-tripviewer-rbac
  template:
    metadata:
      labels:
        app: oh-tripviewer-rbac
    spec:
      containers:
      - name: tripviewer-rbac
        image: registryznq7406.azurecr.io/openhack/tripviewer:latest
        env:
        - name: "TRIPS_API_ENDPOINT"
          value: "http://10.0.189.99"
        - name: "USERPROFILE_API_ENDPOINT"
          value: "http://10.0.49.100"
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80