apiVersion: v1
kind: Service
metadata:
  name: oh-poi-service
  namespace: oh-backend
spec:
  type: ClusterIP
  selector:
    app: oh-poi
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: oh-trips-service
  namespace: oh-backend
spec:
  type: ClusterIP
  selector:
    app: oh-trips
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: oh-user-java-service
  namespace: oh-backend
spec:
  type: ClusterIP
  selector:
    app: oh-user-java
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: oh-userprofile-service
  namespace: oh-backend
spec:
  type: ClusterIP
  selector:
    app: oh-userprofile
  ports:
  - name: http
    port: 80
    targetPort: 80
