apiVersion: v1
kind: Service
metadata:
  name: oh-user-java-service
  namespace: oh-backend
spec:
  type: ClusterIP
  selector:
    app: oh-user-java
  ports:
  - name: http
    port: 80
    targetPort: 80

