apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernets.io/azure-loadbalancer-resource-group: teamsResources
    service.beta.kubernetes.io/azure-dns-label-name: oh-tripviewer-rbac
  name: oh-tripviewer-service
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: oh-tripviewer-rbac
  ports:
  - port: 80